const English = {
    "navLinks": {
      "companyProfile": "Company Profile",
      "aboutUs": "About us",
      "inspectionsAndCertifications": "Inspections & Certifications",
      "training": "Training",
      "approval": "Approval",
      "gallery": "Gallery",
      "contactUs": "Contact us"
    },
    "socialLinks": {
      "youtube": "https://youtube.com",
      "instagram": "https://instagram.com",
      "twitter": "https://x.com",
      "facebook": "https://facebook.com"
    },
    "index": {
      "section1": {
        "heading": "Arabian Bureau of Services",
        "description": "established on 1993 as a 3rd party inspection company for the thorough examination of Lifting Appliances, Lifting Gears, Earthmoving Machineries, Industrial Trucks & QHSE training and consultancy. During this period ABS had grown and expanded in the U.A.E market and established a high strength relationship among its customers whose trust by its judgment. Our judgment against any equipment, machine or accessory gear gives priority of preventing equipment, machine, accessory gear, operators, labors, environment and the property from any accident, deterioration, damage, harm, fatal injuries or death. For more than two decade of operations, ABS has gained much experience in the UAE and has preserved its commitment to provide quality inspection service to all our clients. Qualified and experienced staffs were retained to ensure a continuity of quality inspection & training services."
      },
      "section2": {
        "heading": " Main Core Businesses",
        "points": [
          "Inspection, testing and examination of lifting appliances and lifting gears.",
          "Inspection, testing and examination of Earth moving machinery, Industrial",
          "Examination the competency of the above mentioned equipment and machines operators and conducting safe use of the equipment training courses for them.",
          "Conducting safety & Vocational training courses."
        ]
      },
      "section3": {
        "heading": "Organization",
        "description1": "ABS is continually maintaining a highly qualified inspection and consultancy team, employing the latest technical expertise and paraphernalia, stressing utmost importance in safety, environment, quality, and timely completion task, and complying with all local & international regulations.",
        "description2": " is providing inspection services according to proven methods for inspection based on guidelines and Standard Operating Procedure. The Inspection and consultancy team is well organized by our Technical Manager & Training Manager and doing the task as per his authorization. is providing inspection services according to proven methods for inspection based on guidelines and Standard Operating Procedure. The Inspection and consultancy team is well organized by our Technical Manager & Training Manager and doing the task as per his authorization.",
        "subsections": [
          {
            "title": "Office Facilities",
            "description1": "ABS’s Abu Dhabi office located in the heart of the city & the operations will be handled at Mussafah offices to serve the clients at anytime during the business hours. The communication between the departments and personals are established through phone, e-mails, & verbal conversations.",
            "description2": "All the Certificates and reports are generated by the engineers to avoid delays & errors to ensure the trust of the customer."
          },
          {
            "title": "Work Experience",
            "description": "We ABS work with various prestigious projects with well reputed companies in UAE such as ADNATCO, NMDC, SMG, IMCC group (GPC, IMAC, GSME, CIC, ADCE), GS Engineering, Hyundai, Galfar Engineering, AL Sahraa. We can listed various projects which we handled by us on request."
          },
          {
            "title": "Quality & HSE",
            "description": "ABS is committed with High level of standardization with Quality & HSE. Our Company is certified by LEEA & ENAS for our inspection activities as per iso17020:2012 & our EHSMS system is recently certified by RINA Services for ISO14001:2004: ISO 18001:2007."
          }
        ]
      }
    },
    "about": {
      "section1": {
         "description":" Quality & sustainable life style is essential part of our life. To Ensure the same perfection & unique decision are very important. The current industry is required the quality & certification on everything which ever we dealt with it. <br> With the above idea Arabian Bureau of Services established on 1993 to ensure the quality & impartial inspection as well as the effective training services for its customer. The team is well organized to ensure its services providing to the customer effectively & most efficiently. <br> We registered with all the major oil companies which is providing the services to the nation. We still looking forward to register with international organization to ensure the compliance of the requirements to the international level."
      },
      "section2": {
        "heading": "Arab Services Office",
        "description":`<div class="text-xl">Under his excellent leadership, <span class="font-extrabold">ABS</span> has made progress He is a pioneer in the field of safety inspection and testing, performing many prestigious jobs with a consistent professional approach. He always insists on providing high quality services and follows every possible way to ensure customer satisfaction without compromising on safety and quality.</div>`
      },
      "section3":{
        "heading":" Managing<br> Director’s<br>  Message",
        "description":" Under his excellent leadership,<span class='font-extrabold'>ABS</span> makes major breakthrough in the field of safety inspection and testing undertaking many prestigious jobs with a consistent professional approach. He always insists on high quality services and pursues all possible ways to ensure customer satisfaction without compromising on safety and quality."
      }
      },
      "inspection": {
        "section1": {
          "heading": "INDUSTRY EXPERTS IN<br> KEEPING OUR CUSTOMERS<br> SAFE & COMPLIANT",
          "description":"<p>Arabian Bureau Of Services established in 1993 and providing Engineering Testing, Inspection, Certification of Lifting Equipment, and Training Services. Our objective is to keep our customers both safe and compliant with the relevant legislation and standards.</p><p> Arabian Bureau Of Services are experts in both keeping customer-owned equipment and people both safe and compliant within the workplace. Equipment in the workplace includes lifting accessories and equipment, plant and access equipment, pressure systems, working platforms, fall protections and local exhaust ventilation systems. Our Electrical Testing division provides Electrical Testing, Fixed Wire Testing, and other electrical testing services.</p>"
       },
       "section2": {
        "heading": "TESTING, INSPECTION, &<br> CERTIFICATION SERVICES",
        "description":"Under the Abu Dhabi Municipality (ADM / OSHAD) & Ministry of Industry and Advanced Technology (MOIAT)/Emirates National Accreditation Systems (ENAS) there are various regulations which require employers to ensure that equipment is safe to use, fit for purpose, and thoroughly examined by a competent body. Our team of highly qualified engineers provide thorough examination and certification services on all types of equipment including:",
        "list":'<div class=""><ul class="list-disc h-40 flex flex-col justify-between lg:text-xl pr-4 font-semibold"><li>Cranes & Lifting Equipment and Accessories</li><li>Elevators & Escalators</li><li>Plant and Machinery</li><li>Access Equipment and MEWPS</li><li>Scaffolding & Working Platforms</li></ul></div><div class="lg:m-0 md:m-0 sm:m-0 mt-2 "><ul class="list-disc h-40 flex flex-col justify-between  w-max lg:text-xl text-end font-semibold"> <li class="  max-w-max">Pressure Equipment’s</li> <li class="  max-w-max">Fall Protection</li> <li class="  max-w-max">Electrical Equipment’s &<br> Power Actuated Tools (PAT) Testing</li> <li class="  max-w-max">Access Equipment and MEWPS</li> <li class="  max-w-max">Local Exhaust Ventilation (LEV) systems.</li></ul></div>'

      },
      },
    "training":{
       "section1":{
         "heading":"TRAINING<br>SERVICES",
         "description":"<div >Abu Dhabi Public Health Centre (ADPHC) & The Abu Dhabi Centre for Technical and Vocational Education and Training (ACTVET) requires all employers to provide suitable and relevant training within the work place to ensure that employees are able to work safely at all times.</div>",
        "description2":" <p>Abu Dhabi Public Health Centre (ADPHC) & The Abu Dhabi Centre for Technical and Vocational Education and Training (ACTVET) requires all employers to provide suitable and relevant training within the work place to ensure that employees are able to work safely at all times.</p><p class='mt-8'>Our training division offers a wide range of accredited training courses covering the following categories:</p>"
        },
        "section2":{
          "list" :" <ul  class='list-disc ul-traning lg:text-2xl md:text-2xl text-xl font-bold'><li>General Health and Safety</li><li>Lifting Equipment and Lifting Operations</li><li>Working at Height</li><li>Forklift and Lift Trucks</li><li>Plant and Machinery Operations</li><li>Access Equipment and MEWP’s</li><li>Scaffolding Awareness & Competent Person</li></ul>"
        }
    } ,
    "approvals" :{
      "title":"Approvals",
    },
    "gallery" :{
     "section1":{
       "title1":"ADNOC Vessel mid ship crane load testing",
       "title2":"Proof load testing of lifting frame 500 ton",
     },
     "section2":{
      "heading":"Arena trusses load tested in MENA region",
      "title1":"ADNOC Vessel embarkation ladder load testing",
      "title2":"Air craft docking platform load testing",
      "description":"For Testing <br>Please Contact us"
    }
    },
    "contact":{
      "title1":"For Enquire & Complaints",
      "title2":"Certificates",
    },
    "footer": {
      "links": {
        "Profile": "Company Profile",
        "About": "About",
        "Inspections": "Inspections & Certifications",
        "training": "Training",
        "approvals": "Approvals",
        "gallery": "Gallery",
        "contact": "Contact"
      },
      "companyInfo": {
        "name": "Arabian Bureau of Services",
        "address": "P.O.Box 47133 - Musaffah",
        "phone": "+971 2 5511520",
        "email": "abs@abosad.com"
      }
    }

  }
