const English = {
    "navLinks": {
      "companyProfile": "Company Profile",
      "aboutUs": "About us",
      "inspectionsAndCertifications": "Inspections & Certifications",
      "training": "Training",
      "approval": "Approval",
      "gallery": "Gallery",
      "contactUs": "Contact us"
    },
    "socialLinks": {
      "youtube": "https://youtube.com",
      "instagram": "https://instagram.com",
      "twitter": "https://x.com",
      "facebook": "https://facebook.com"
    },
    "index": {
      "section1": {
        "heading": "Arabian Bureau of Services",
        "description": "established on 1993 as a 3rd party inspection company for the thorough examination of Lifting Appliances, Lifting Gears, Earthmoving Machineries, Industrial Trucks & QHSE training and consultancy. During this period ABoS had grown and expanded in the U.A.E market and established a high strength relationship among its customers whose trust by its judgment. Our judgment against any equipment, machine or accessory gear gives priority of preventing equipment, machine, accessory gear, operators, labors, environment and the property from any accident, deterioration, damage, harm, fatal injuries or death. For more than two decade of operations, ABoS has gained much experience in the UAE and has preserved its commitment to provide quality inspection service to all our clients. Qualified and experienced staffs were retained to ensure a continuity of quality inspection & training services."
      },
      "section2": {
        "heading": " Main Core Businesses",
        "points": [
          "Inspection, testing and examination of lifting appliances and lifting gears.",
          "Inspection, testing and examination of Earth moving machinery, Industrial",
          "Examination the competency of the above mentioned equipment and machines operators and conducting safe use of the equipment training courses for them.",
          "Conducting safety & Vocational training courses."
        ]
      },
      "section3": {
        "heading": "Organization",
        "description1": "ABoS is continually maintaining a highly qualified inspection and consultancy team, employing the latest technical expertise and paraphernalia, stressing utmost importance in safety, environment, quality, and timely completion task, and complying with all local & international regulations.",
        "description2": " is providing inspection services according to proven methods for inspection based on guidelines and Standard Operating Procedure. The Inspection and consultancy team is well organized by our Technical Manager & Training Manager and doing the task as per his authorization. is providing inspection services according to proven methods for inspection based on guidelines and Standard Operating Procedure. The Inspection and consultancy team is well organized by our Technical Manager & Training Manager and doing the task as per his authorization.",
        "subsections": [
          {
            "title": "Office Facilities",
            "description1": "ABOS’s Abu Dhabi office located in the heart of the city & the operations will be handled at Mussafah offices to serve the clients at anytime during the business hours. The communication between the departments and personals are established through phone, e-mails, & verbal conversations.",
            "description2": "All the Certificates and reports are generated by the engineers to avoid delays & errors to ensure the trust of the customer."
          },
          {
            "title": "Work Experience",
            "description": "We ABoS work with various prestigious projects with well reputed companies in UAE such as ADNATCO, NMDC, SMG, IMCC group (GPC, IMAC, GSME, CIC, ADCE), GS Engineering, Hyundai, Galfar Engineering, AL Sahraa. We can listed various projects which we handled by us on request."
          },
          {
            "title": "Quality & HSE",
            "description": "ABoS is committed with High level of standardization with Quality & HSE. Our Company is certified by LEEA & ENAS for our inspection activities as per iso17020:2012 & our EHSMS system is recently certified by RINA Services for ISO14001:2004: ISO 18001:2007."
          }
        ]
      }
    },
    "about": {
      "section1": {
        "heading": "المكتب العربي للخدمات",
         "description":"Quality & sustainable life style is essential part of our life. To Ensure the same perfection & unique decision are very important. The current industry is required the quality & certification on everything which ever we dealt with it.With the above idea Arabian Bureau of Services established on 1993 to ensure the quality & impartial inspection as well as the effective training services for its customer. The team is well organized to ensure its services providing to the customer effectively & most efficiently.We registered with all the major oil companies which is providing the services to the nation. We still looking forward to register with international organization to ensure the compliance of the requirements to the international level."
      }
     },
    "footer": {
      "links": {
        "training": "Training",
        "approvals": "Approvals",
        "gallery": "Gallery",
        "contact": "Contact"
      },
      "companyInfo": {
        "name": "Arabian Bureau of Services",
        "address": "P.O.Box 47133 - Musaffah",
        "phone": "+971 2 5511520",
        "email": "abos@abosad.com"
      }
    }

  }
